### PR TITLE
Fredy's Pull Request # 1

### PR DESCRIPTION
**Pull request by FredyLRincon**
## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)
We processed, cleaned, and prepared the dataset to analyze customer purchasing behaviour based on membership type. We added visualizations for exploratory data analysis and developed a regression model, including features like membership type and total spend, to predict the number of items purchased.

## What did you learn from the changes you have made?
We learned that membership type slightly influences the number of items purchased, but total spend is a stronger predictor. Our model, including total spend, explains about 95.3% of the variance in items purchased, indicating a perfect fit.

## Was there another approach you were thinking about making? If so, what approach(es) were you thinking of?
We considered using more complex models to capture nonlinear relationships and improve predictive power.

## Were there any challenges? If so, what issue(s) did you face? How did you overcome it?
We faced internal errors while generating visualizations within the environment. We overcame this by providing the code for local execution, ensuring the user could generate the visualizations with the requested custom colours on their machine.

## Checklist
- [X] I can confirm that my changes are working as intended

### CODE REVIEW

**Comment by FredyLRincon** [comment]
Hi team,
I just did my first pull request.
Please be gentle :D 

Cheers,

**FREDY RINCON**

**Comment by JzfL** [comment]
Looks perfect to me! Nothing better I can do.

**Comment by efantinatti** [comment]
Great work! Deserves a merge!

**Comment by FredyLRincon** [comment]
Thank you for taking the time to reviewing the PR and for the comments @efantinatti  and @JzfL

**Comment by FredyLRincon** [comment]
Thanks for merging, @efantinatti

**Pull request merged**
