### PR TITLE
Ernani Fantinatti contribution for worflow, project explanation and d…

### PR DESCRIPTION
**Pull request by efantinatti**
…iagram.

## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)
A: Contributing to the project documentation.

## What did you learn from the changes you have made?
A: Best practices on Documentation.

## Was there another approach you were thinking about making? If so, what approach(es) were you thinking of?
A: No.

## Were there any challenges? If so, what issue(s) did you face? How did you overcome it?
A: n/a

## Checklist
- [X] I can confirm that my changes are working as intended

### CODE REVIEW

**Comment by JzfL** [comment]
Great start and workflow, approved

**Review by JzfL — APPROVED** [review]
Great work!

**Review by FredyLRincon — COMMENTED** [review]
Hi Ernani,
Thanks for putting all this together!
This is awesome. Does this mean we will implement all this? If yes, it looks ambitious!

Let's discuss this with the rest of the group. I believe we can focus on the low-hanging fruit, and if there is enough time, we can continue improving the notebook.

**Review by FredyLRincon — APPROVED** [review]

**Review by FredyLRincon — APPROVED** [review]

**Comment by cinnabon911** [comment]
approved

**Review by cinnabon911 — COMMENTED** [review]
looks good

**Review by alisonwu2019 — COMMENTED** [review]
lgtm

**Pull request merged**
